import chalk from "chalk"

export const primary = "#66cd32"
export const secondary = "#656565"

/* eslint-disable max-len */
export const logo = chalk`
{bgBlack.black                                                                                              }
{bgBlack.black                                   }{bgBlack.hex("${primary}") CLLfftttttttttttttttffLLC}{bgBlack.black                                   }
{bgBlack.black                             }{bgBlack.hex("${primary}") CLfttt1tttttttttttttttttttt111ttttfL}{bgBlack.black                              }
{bgBlack.black                         }{bgBlack.hex("${primary}") CLtttttttttt1tttttttttttttttttttttttttt1ttfL}{bgBlack.black                          }
{bgBlack.black                      }{bgBlack.hex("${primary}") Cfttttttt11tttffLLC}{bgBlack.black              }{bgBlack.hex("${primary}") CLLffttt11tttttttfC}{bgBlack.black                      }
{bgBlack.black                   }{bgBlack.hex("${primary}") CfttttttttttfLC}{bgBlack.black                            }{bgBlack.hex("${primary}") CLftttttt1tttf}{bgBlack.black                    }
{bgBlack.black                 }{bgBlack.hex("${primary}") LttttttttttL}{bgBlack.black                                      }{bgBlack.hex("${primary}") LfttttttttfC}{bgBlack.black                 }
{bgBlack.black               }{bgBlack.hex("${primary}") LttttttttfL}{bgBlack.black                                            }{bgBlack.hex("${primary}") LfttttttttL}{bgBlack.black               }
{bgBlack.black             }{bgBlack.hex("${primary}") Lttttttttf}{bgBlack.black                                                  }{bgBlack.hex("${primary}") fttttttttC}{bgBlack.black             }
{bgBlack.black            }{bgBlack.hex("${primary}") ft1tttttL}{bgBlack.black                                                      }{bgBlack.hex("${primary}") Ltttttttf}{bgBlack.black            }
{bgBlack.black          }{bgBlack.hex("${primary}") Lt1ttt1tf}{bgBlack.black                                                          }{bgBlack.hex("${primary}") ftttttttC}{bgBlack.black          }
{bgBlack.black         }{bgBlack.hex("${primary}") ftttt1tfC}{bgBlack.black                                                            }{bgBlack.hex("${primary}") CfttttttL}{bgBlack.black         }
{bgBlack.black        }{bgBlack.hex("${primary}") tttttttL}{bgBlack.black                                                                }{bgBlack.hex("${primary}") Lt1ttttf}{bgBlack.black        }
{bgBlack.black       }{bgBlack.hex("${primary}") fttttttL}{bgBlack.black                                                                  }{bgBlack.hex("${primary}") Lt1ttttf}{bgBlack.black       }
{bgBlack.black      }{bgBlack.hex("${primary}") fttttttC}{bgBlack.black                                                                    }{bgBlack.hex("${primary}") Cttttttf}{bgBlack.black      }
{bgBlack.black     }{bgBlack.hex("${primary}") fttttttL}{bgBlack.black                                                                      }{bgBlack.hex("${primary}") CttttttL}{bgBlack.black     }
{bgBlack.black    }{bgBlack.hex("${primary}") CttttttL}{bgBlack.black            }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") t}{bgBlack.black     }{bgBlack.hex("${secondary}") f1i}{bgBlack.bold.white mmmmmmm}{bgBlack.hex("${secondary}") if}{bgBlack.black          }{bgBlack.hex("${secondary}") f1i}{bgBlack.bold.white mmmmmmm}{bgBlack.hex("${secondary}") it}{bgBlack.black                 }{bgBlack.hex("${primary}") LttttttC}{bgBlack.black    }
{bgBlack.black    }{bgBlack.hex("${primary}") ttttttf}{bgBlack.black            }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black  }{bgBlack.hex("${secondary}") Li}{bgBlack.bold.white mmmmmmmmmmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black L   L}{bgBlack.hex("${secondary}") 1}{bgBlack.bold.white mmmmmmmmmmmmmm}{bgBlack.hex("${secondary}") if}{bgBlack.black               }{bgBlack.hex("${primary}") ftttttt}{bgBlack.black    }
{bgBlack.black   }{bgBlack.hex("${primary}") Ltttttt}{bgBlack.black             }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmmmmmmmmmmmmmmmmmmmmmm}{bgBlack.hex("${secondary}") f}{bgBlack.black  }{bgBlack.hex("${secondary}") t}{bgBlack.bold.white mmmmmmmmmmmmmmmmmm}{bgBlack.hex("${secondary}") t}{bgBlack.black              }{bgBlack.hex("${primary}") CttttttC}{bgBlack.black   }
{bgBlack.black   }{bgBlack.hex("${primary}") ftttttf}{bgBlack.black             }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmmmmmm}{bgBlack.hex("${secondary}") tL}{bgBlack.black      }{bgBlack.hex("${secondary}") fi}{bgBlack.bold.white mmmmmmmmmmmm}{bgBlack.hex("${secondary}") 1f}{bgBlack.black      }{bgBlack.hex("${secondary}") f1}{bgBlack.bold.white mmmmmmmm}{bgBlack.hex("${secondary}") t}{bgBlack.black              }{bgBlack.hex("${primary}") LtttttL}{bgBlack.black   }
{bgBlack.hex("${primary}")  Lf1ttttC}{bgBlack.black             }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmmmm}{bgBlack.hex("${secondary}") f}{bgBlack.black           }{bgBlack.hex("${secondary}") Li}{bgBlack.bold.white mmmmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black           }{bgBlack.hex("${secondary}") L1}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${primary}") tttttt}{bgBlack.black   }
{bgBlack.hex("${primary}")  ftttttt}{bgBlack.black              }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmmm}{bgBlack.hex("${secondary}") f}{bgBlack.black             }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black              }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${primary}") ttttttC}{bgBlack.black  }
{bgBlack.hex("${primary}")  ftttttt}{bgBlack.black              }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${primary}") ttttttC}{bgBlack.black  }
{bgBlack.hex("${primary}")  ttttttt}{bgBlack.black              }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${primary}") ttt1ttC}{bgBlack.black  }
{bgBlack.hex("${primary}")  ftttttt}{bgBlack.black              }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${primary}") CCCLLL}{bgBlack.black   }
{bgBlack.hex("${primary}")  Ltttt1t}{bgBlack.black              }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black                       }
{bgBlack.hex("${primary}")  CftttttL}{bgBlack.black             }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black                       }
{bgBlack.black   }{bgBlack.hex("${primary}") L1ttttt}{bgBlack.black             }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black              }{bgBlack.hex("${secondary}") C}{bgBlack.bold.white ttt}{bgBlack.hex("${secondary}") f}{bgBlack.black     }
{bgBlack.black   }{bgBlack.hex("${primary}") CttttttC}{bgBlack.black            }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black             }{bgBlack.hex("${secondary}") t}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") t}{bgBlack.black    }
{bgBlack.black    }{bgBlack.hex("${primary}") ftttttf}{bgBlack.black            }{bgBlack.hex("${secondary}") L}{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") 1}{bgBlack.black               }{bgBlack.bold.white mmmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black               }{bgBlack.hex("${secondary}") i}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") i}{bgBlack.black             }{bgBlack.hex("${secondary}") t}{bgBlack.bold.white mmmmm}{bgBlack.hex("${secondary}") t}{bgBlack.black    }
{bgBlack.black     }{bgBlack.hex("${primary}") ttttttf}{bgBlack.black            }{bgBlack.hex("${secondary}") t}{bgBlack.bold.white 11111}{bgBlack.hex("${secondary}") f}{bgBlack.black               }{bgBlack.hex("${secondary}") t}{bgBlack.bold.white 11111}{bgBlack.hex("${secondary}") f}{bgBlack.black               }{bgBlack.hex("${secondary}") f}{bgBlack.bold.white 11111}{bgBlack.hex("${secondary}") f}{bgBlack.black              }{bgBlack.hex("${secondary}") C}{bgBlack.bold.white t1t}{bgBlack.hex("${secondary}") L}{bgBlack.black     }
{bgBlack.black     }{bgBlack.hex("${primary}") Lttttttf}{bgBlack.black                                                                                  }
{bgBlack.black      }{bgBlack.hex("${primary}") LttttttL}{bgBlack.black                                                                                 }
{bgBlack.black       }{bgBlack.hex("${primary}") Lttttttf}{bgBlack.black                                                                  }{bgBlack.hex("${primary}") ftfL}{bgBlack.black           }
{bgBlack.black        }{bgBlack.hex("${primary}") LtttttttC}{bgBlack.black                                                              }{bgBlack.hex("${primary}") Ctt11ttf}{bgBlack.black         }
{bgBlack.black         }{bgBlack.hex("${primary}") CtttttttL}{bgBlack.black                                                            }{bgBlack.hex("${primary}") fttttttf}{bgBlack.black          }
{bgBlack.black           }{bgBlack.hex("${primary}") ftttttttL}{bgBlack.black                                                        }{bgBlack.hex("${primary}") Ltttttttf}{bgBlack.black           }
{bgBlack.black            }{bgBlack.hex("${primary}") Lt1ttttttL}{bgBlack.black                                                    }{bgBlack.hex("${primary}") LtttttttfC}{bgBlack.black            }
{bgBlack.black              }{bgBlack.hex("${primary}") Lt1ttttttL}{bgBlack.black                                                }{bgBlack.hex("${primary}") Lttttt1ttL}{bgBlack.black              }
{bgBlack.black                }{bgBlack.hex("${primary}") Lt1tttttttL}{bgBlack.black                                          }{bgBlack.hex("${primary}") Ltttttt1tfL}{bgBlack.black                }
{bgBlack.black                  }{bgBlack.hex("${primary}") LttttttttttfC}{bgBlack.black                                  }{bgBlack.hex("${primary}") CftttttttttfC}{bgBlack.black                  }
{bgBlack.black                     }{bgBlack.hex("${primary}") Ltttttttt1ttfLC}{bgBlack.black                        }{bgBlack.hex("${primary}") CLftttttttt1tfL}{bgBlack.black                     }
{bgBlack.black                        }{bgBlack.hex("${primary}") LtttttttttttttttffLLL}{bgBlack.black CCCCC}{bgBlack.hex("${primary}") LLLffttttt1ttttttttfL}{bgBlack.black                        }
{bgBlack.black                            }{bgBlack.hex("${primary}") ftttt1ttttttt1ttt111t1tttttttttt11tttfLC}{bgBlack.black                           }
{bgBlack.black                               }{bgBlack.hex("${primary}") CLLftttttttttttttttttttttttttfLC}{bgBlack.black                                }
{bgBlack.black                                        }{bgBlack.hex("${primary}") LfffftttttfffLLC}{bgBlack.black                                       }
{bgBlack.black                                                                                              }
`
/* eslint-enable max-len */

/* eslint-disable-next-line no-console */
export default () => console.log(logo)
